language: node_js
node_js:
  - node
before_script:
  - cd website
  - npm install
script: 
  - npm run build
deploy:
  local-dir: website/_site
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    tags: true
