module.exports = {
    DOCSSITE_ROOT_SUBDIR: process.env.DOCSSITE_ROOT_SUBDIR,
    DOCSSITE_WRITE_VERSION: process.env.DOCSSITE_WRITE_VERSION,
    DOCSSITE_HISTORY_URL: process.env.DOCSSITE_HISTORY_URL,
    DOCSSITE_VERSION: process.env.DOCSSITE_VERSION
};